name: Post

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  
jobs:
  generate-post:
    runs-on: ubuntu-latest
    name: Post
    steps:
    
      - name: TghaAction
        id: TghaAction
        uses: nurzhanme/TghaAction@0.0.1
        with:
          token: ${{ secrets.TOKEN }}
          chat-id: ${{ secrets.CHAT_ID }}
